name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python -m pip install -r requirements_dev.txt

      - name: Run tests
        run: coverage run --source=./sa_repository -m pytest tests

      - name: Coverage
        run: coverage report
